### ISSUE TITLE
JSX highlight not working

### ISSUE THREAD

**Issue by mybadclan** [datsfilipe/min-theme.nvim#5] opened 2024-05-25 22:49 UTC
Min Theme apply colors to jsx syntax like image below:

![screenshot-dark](https://github.com/datsfilipe/min-theme.nvim/assets/93738219/2fa0b75a-d7bf-4746-808b-bf43a8c6d2fc)

When I use min-theme.nvim, I have the result below:

![Screenshot_20240525_194444](https://github.com/datsfilipe/min-theme.nvim/assets/93738219/600b6f54-55a0-48cc-8d65-d5052c0da43f)

**Comment by datsfilipe** [comment] 2024-05-25 22:54
Do you have your `treesitter` correctly setup? and you installed the parser for `jsx`?

**Comment by mybadclan** [comment] 2024-05-25 23:45
I run `:checkhealth nvim-treesitter` and get the result below:

![Screenshot_20240525_203308](https://github.com/datsfilipe/min-theme.nvim/assets/93738219/d4a38ad8-f643-4069-a5bd-39ff9ff68219)

![Screenshot_20240525_203528](https://github.com/datsfilipe/min-theme.nvim/assets/93738219/3f63a4a9-bb1d-456b-b54d-5ca57bd15d01)

My treesitter config is like the code below:

```lua
return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  config = function()
    -- Tree sitter config
    local config = require("nvim-treesitter.configs")

    config.setup({
      ensure_installed = { "lua", "javascript", "typescript", "html", "json", "css", "tsx" },

      -- auto_install = true,
      highlight = {
	enable = true,
	additional_vim_regex_highlighting = false,
      },
      indent = { enable = true },
    })
  end,
}
```

**Comment by datsfilipe** [comment] 2024-05-27 12:24
I have these lines configured in mine `treesitter` config, see if it helps you:
```lua
local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
parser_config.tsx.filetype_to_parsername = { 'javascript', 'typescript.tsx' }
```
The theme works well for me in `tsx`/`jsx` files, so I think it probably is some configuration problem.

**Comment by deyvisonIO** [comment] 2024-07-17 17:15
I have the same problem, it happened after I updated treesitter and to the latest version of neovim.

**Comment by datsfilipe** [comment] 2024-07-18 00:10
I'll try to take a look at it, thanks for reporting guys 👍🏻

**Comment by datsfilipe** [comment] 2024-07-20 20:58
okay, did some progress with the `jsx`/`tsx` highlights:

![image](https://github.com/user-attachments/assets/2dade82f-5c6d-48ec-a374-9a280fce43e6)

Btw, in this repo there's [this file](https://github.com/datsfilipe/min-theme.nvim/blob/main/init.lua) which contains basic config I use for development, so you might want to check the `treesitter` config there if you still have problems.

Gonna close it as resolved for now, please update your plugin locally, try out the new version and let me now if you still having this problem.

**Closed as completed by datsfilipe** 2024-07-20 20:58 UTC
Labels: bug

**Comment by deyvisonIO** [comment] 2024-07-21 18:02
After the update the problem is solved! Thanks!

**Comment by mybadclan** [comment] 2024-07-27 17:41
It's work. Thank you very much! :rocket: :rocket:
